framework:
    messenger:
        failure_transport: failed

        transports:
            # For async processing (requires messenger_messages table)
            async: 
                dsn: 'doctrine://default'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            
            # For failed messages
            failed: 'doctrine://default?queue_name=failed'
            
            # For synchronous processing (immediate)
            sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Choose ONE of these options for email messages:

            # OPTION 1: For async processing (requires messenger_messages table)
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            
            # OPTION 2: For immediate sending (recommended for your case)
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            
            # Other message types
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
