symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600 # 1 hour in seconds
    throttle_limit: 3600 # 1 hour in seconds
    enable_garbage_collection: true