# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mechanics_directory: '%kernel.project_dir%/public/uploads/mechanics'
    assemblyai.api_key: '%env(ASSEMBLYAI_API_KEY)%'
    google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    google_redirect_uri: '%env(GOOGLE_REDIRECT_URI)%'
    google_calendar_id: 'primary'

services:
    _defaults:
            autowire: true      # Automatically injects dependencies in your services.
            autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # default configuration for services in *this* file
    Fusonic\MessengerMailerBundle\EmailAttachmentHandler\FilesystemAttachmentHandler:
        arguments:
            $attachmentsDirectory: '%kernel.project_dir%/var/email-attachments'
    
    
          

    

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\AssemblyAiService:
        arguments:
            $assemblyAiApiKey: '%assemblyai.api_key%'
            $logger: '@logger'

    App\Service\GoogleCalendarService:
        arguments:
            $clientId: '%google_client_id%'
            $clientSecret: '%google_client_secret%'
            $redirectUri: '%env(APP_URL)%/assignment/google/callback'
            $calendarId: '%google_calendar_id%'
            $projectDir: '%kernel.project_dir%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
