parameters:
  profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
  warehouse_images_directory: '%kernel.project_dir%/public/images/Warehouse'
  avatar_directory: '%kernel.project_dir%/public/uploads/avatars'
  


services:
    App\Security\UserChecker:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
   
    App\Service\AvatarService: ~

    # Twig global
    App\Twig\AvatarExtension:
        tags: ['twig.extension']
    
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'
    
 
    # No special configuration needed for FaceAuthenticator - autowiring will handle it

    