<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCIG6Rb9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCIG6Rb9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCIG6Rb9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCIG6Rb9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCIG6Rb9\App_KernelDevDebugContainer([
    'container.build_hash' => 'CIG6Rb9',
    'container.build_id' => 'cc50d901',
    'container.build_time' => 1745074865,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCIG6Rb9');
