<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1xmdd8A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1xmdd8A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1xmdd8A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1xmdd8A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1xmdd8A\App_KernelDevDebugContainer([
    'container.build_hash' => '1xmdd8A',
    'container.build_id' => 'ab8385c6',
    'container.build_time' => 1746651880,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1xmdd8A');
