<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCppQ0p1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCppQ0p1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCppQ0p1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCppQ0p1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCppQ0p1\App_KernelDevDebugContainer([
    'container.build_hash' => 'CppQ0p1',
    'container.build_id' => 'b01161b7',
    'container.build_time' => 1746136379,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCppQ0p1');
